### ISSUE TITLE
[Troubleshooting] Failure to dump OTP.bin with v1.0

### ISSUE THREAD

**Issue by VariablePwn** [shinyquagsire23/wii_u_modchip#9]
I've tried all day to get OTP.bin to dump with PRSHhax, but unfortunately it would not work at all.
After reading through the GBATemp articles, it seems someone dried using an older version and it worked for them.
I flash v0.8 onto my pico, and overwrote the files on the SD card, and on my second attempt successfully dumped OTP.bin (at least according to the console).

**Comment by jan-hofmeier** [comment]
This is fixed in the v1.1 release. (was a bug in minute)
